/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcorner;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author HIRAY-MCA
 */
public class Orders extends javax.swing.JInternalFrame {
    boolean setRateEnable = false;
    int Chicken, Veg, Fries, Burger;
    int Total=0;
    int GrandTotal;
    int OrderNo;
    JComboBox cmbFriesAdd;
//-------------------Database Stuff--------------------
    Connection conn;
    Statement stmt;
    ResultSet rs;
    

    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
        changeRates();
       
        
        cmbFriesAdd = new JComboBox();     //just for lulz so that calculate() wont return an error for missing Fries ComboBox.
        txtAmtChange.setEditable(false);
        
//-------------------Database Stuff--------------------
        databaseConnect();  //to connect to db
        readFromDB();       //to read initial rate values from db
        setLastOrderNo();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrders = new javax.swing.JLabel();
        txtBurgerQty = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        lblType1 = new javax.swing.JLabel();
        txtChickenQty = new javax.swing.JTextField();
        txtVegQty = new javax.swing.JTextField();
        txtFriesQty = new javax.swing.JTextField();
        chkChicken = new javax.swing.JCheckBox();
        chkVeg = new javax.swing.JCheckBox();
        chkFries = new javax.swing.JCheckBox();
        chkBurger = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        lblRate = new javax.swing.JLabel();
        txtChickenRate = new javax.swing.JTextField();
        txtVegRate = new javax.swing.JTextField();
        txtFriesRate = new javax.swing.JTextField();
        txtBurgerRate = new javax.swing.JTextField();
        btnEditRates = new javax.swing.JButton();
        cmbChickenAdd = new javax.swing.JComboBox<>();
        cmbVegAdd = new javax.swing.JComboBox<>();
        cmbBurgerAdd = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        lblChickenTotal = new javax.swing.JLabel();
        lblVegTotal = new javax.swing.JLabel();
        lblFriesTotal = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        lblBurgerTotal = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtAmtRecvd = new javax.swing.JTextField();
        lblTotal3 = new javax.swing.JLabel();
        lblTotal4 = new javax.swing.JLabel();
        lblTotal5 = new javax.swing.JLabel();
        txtAmtChange = new javax.swing.JTextField();
        btnGetChange = new javax.swing.JButton();
        lblOrder = new javax.swing.JLabel();
        lblLastOrderNo = new javax.swing.JLabel();
        lblOrder1 = new javax.swing.JLabel();
        lblCurrOrderNo1 = new javax.swing.JLabel();

        setClosable(true);

        lblOrders.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblOrders.setText("Orders");

        txtBurgerQty.setText("1");

        lblType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblType.setText("Qty.");

        lblType1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblType1.setText("Type");

        txtChickenQty.setText("1");

        txtVegQty.setText("1");

        txtFriesQty.setText("1");

        chkChicken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkChicken.setText("Chicken Frankie");

        chkVeg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkVeg.setText("Veg. Frankie");
        chkVeg.setActionCommand("Veg.Frankie");

        chkFries.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkFries.setText("Fries");

        chkBurger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkBurger.setText("Burger");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblRate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRate.setText("Rate");

        btnEditRates.setText("Edit Rates");
        btnEditRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRatesActionPerformed(evt);
            }
        });

        cmbChickenAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Butter 10/-", "Cheese 10/-" }));

        cmbVegAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Butter 10/-", "Cheese 10/-" }));

        cmbBurgerAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Butter 10/-", "Cheese 10/-" }));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("Total");

        lblTotal1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal1.setText("----------------------------------------------------------------------------------------------------------------------------------------");

        lblTotal2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal2.setText("Grand Total = ");

        lblChickenTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblChickenTotal.setText("0");

        lblVegTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVegTotal.setText("0");

        lblFriesTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFriesTotal.setText("0");

        lblGrandTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGrandTotal.setText("0");

        lblBurgerTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBurgerTotal.setText("0");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtAmtRecvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetChangeActionPerformed(evt);
            }
        });

        lblTotal3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal3.setText("Change Calculator");

        lblTotal4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal4.setText("Amt. Received");

        lblTotal5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal5.setText("Change");

        btnGetChange.setText("Get Change");
        btnGetChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetChangeActionPerformed(evt);
            }
        });

        lblOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOrder.setText("Last Order No:");

        lblLastOrderNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLastOrderNo.setText("0");

        lblOrder1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOrder1.setText("Current Order No:");

        lblCurrOrderNo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrOrderNo1.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(lblOrders)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditRates))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblTotal1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblType1)
                                .addGap(358, 358, 358)
                                .addComponent(lblType)
                                .addGap(111, 111, 111)
                                .addComponent(lblRate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkChicken)
                                        .addGap(298, 298, 298)
                                        .addComponent(txtChickenQty, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkVeg)
                                            .addComponent(chkFries)
                                            .addComponent(chkBurger))
                                        .addGap(324, 324, 324)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVegQty, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtFriesQty, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtBurgerQty, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVegRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFriesRate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBurgerRate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtChickenRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbChickenAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbVegAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBurgerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblVegTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblChickenTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFriesTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblBurgerTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnGetChange)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTotal4)
                                        .addComponent(lblTotal5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAmtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAmtRecvd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(35, 35, 35)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrOrderNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTotal2)
                        .addGap(88, 88, 88)
                        .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrders)
                    .addComponent(btnEditRates))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblTotal3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblType)
                                .addComponent(lblRate)
                                .addComponent(lblTotal)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(chkChicken)
                                                    .addComponent(txtChickenQty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtChickenRate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbChickenAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(chkVeg)
                                                    .addComponent(txtVegQty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtVegRate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbVegAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(chkFries)
                                                    .addComponent(txtFriesQty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFriesRate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtAmtRecvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblTotal4))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTotal5)
                                                    .addComponent(txtAmtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnGetChange)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(chkBurger)
                                            .addComponent(txtBurgerQty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBurgerRate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbBurgerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblChickenTotal)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblVegTotal)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblFriesTotal)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBurgerTotal)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotal2)
                                    .addComponent(lblGrandTotal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCurrOrderNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(115, 115, 115))))
                    .addComponent(lblType1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRatesActionPerformed
        if(setRateEnable==false){   //Before changing the rates
            setRateEnable=true;
            changeRates();
            btnEditRates.setText("Set Rates");
            btnEditRates.setBackground(Color.RED);
            btnEditRates.setForeground(Color.WHITE);
        }
        else{   //After changing the rates. To save the rates.
            setRateValues(toInt(txtChickenRate.getText()), toInt(txtVegRate.getText()), toInt(txtFriesRate.getText()), toInt(txtBurgerRate.getText()));
            
            storeToDB();    //stores the newly changed rates to Database
            
            btnEditRates.setText("Edit Rates");
            btnEditRates.setBackground(Color.LIGHT_GRAY);
            btnEditRates.setForeground(Color.BLACK);
            setRateEnable=false;
            changeRates();
        }
        
    }//GEN-LAST:event_btnEditRatesActionPerformed

    private boolean rateNotSet(){
        boolean bool;
        
        if(btnEditRates.getText().equals("Set Rates") || setRateEnable==true)
            bool = true;
        else
            bool = false;
        
        return bool;
    }
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(rateNotSet()==true){
            JOptionPane.showMessageDialog(null, "ERROR: Set the rates first");
        }
        else{
        OrderNo++;
        
        calculate(chkChicken, txtChickenQty, txtChickenRate, lblChickenTotal, cmbChickenAdd);
        calculate(chkVeg, txtVegQty, txtVegRate, lblVegTotal, cmbVegAdd);
        calculate(chkFries, txtFriesQty, txtFriesRate, lblFriesTotal, cmbFriesAdd);
        calculate(chkBurger, txtBurgerQty, txtBurgerRate, lblBurgerTotal, cmbBurgerAdd);
        
        GrandTotal = toInt(lblChickenTotal.getText()) + toInt(lblVegTotal.getText()) + toInt(lblFriesTotal.getText()) + toInt(lblBurgerTotal.getText());
        lblGrandTotal.setText(String.format("%s", GrandTotal));
        
        JOptionPane.showMessageDialog(null, "Order Saved");
        setLastOrderNo();
        btnClearActionPerformed(evt);   //Clicks clear button for new Order
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        if(rateNotSet()==true){
            JOptionPane.showMessageDialog(null, "ERROR: Set the rates first");
        }
        else{
        justCalculate(chkChicken, txtChickenQty, txtChickenRate, lblChickenTotal, cmbChickenAdd);
        justCalculate(chkVeg, txtVegQty, txtVegRate, lblVegTotal, cmbVegAdd);
        justCalculate(chkFries, txtFriesQty, txtFriesRate, lblFriesTotal, cmbFriesAdd);
        justCalculate(chkBurger, txtBurgerQty, txtBurgerRate, lblBurgerTotal, cmbBurgerAdd);
        
        GrandTotal = toInt(lblChickenTotal.getText()) + toInt(lblVegTotal.getText()) + toInt(lblFriesTotal.getText()) + toInt(lblBurgerTotal.getText());
        lblGrandTotal.setText(String.format("%s", GrandTotal));
        }
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        JCheckBox chkArray[] = {chkChicken, chkVeg, chkFries, chkBurger};
        JComboBox cmbArray[] = {cmbChickenAdd, cmbVegAdd, cmbBurgerAdd};
        JTextField txtQtyArray[] = {txtChickenQty, txtVegQty, txtFriesQty, txtBurgerQty};
        JLabel lblArray[] = {lblChickenTotal, lblVegTotal, lblFriesTotal, lblBurgerTotal, lblGrandTotal};
        
        for(JCheckBox chk: chkArray)
            chk.setSelected(false);
        
        for(JComboBox cmb: cmbArray)
            cmb.setSelectedIndex(0);
        
        for(JTextField qty: txtQtyArray)
            qty.setText("1");
        
        readFromDB();   //reads the rates stored in database and sets them.
        
        for(JLabel lbl: lblArray)
            lbl.setText("0");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnGetChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetChangeActionPerformed
        int recvd, change, total;
        recvd = toInt(txtAmtRecvd.getText());
        total = toInt(lblGrandTotal.getText());
        
        if(recvd < total){
            JOptionPane.showMessageDialog(null, "Amount received cannot be less than total");
        }
        else{
        change = recvd - total;
        txtAmtChange.setText(String.format("%s", change));
        }
    }//GEN-LAST:event_btnGetChangeActionPerformed
    
    public void calculate(JCheckBox item, JTextField itemQty, JTextField itemRate, JLabel totalLabel, JComboBox itemCmb){
        if (item.isSelected()){
           Total = itemCmb.getSelectedIndex() > 0 ? 10:0;
           Total += toInt(itemQty.getText()) * toInt(itemRate.getText());
           totalLabel.setText(String.format("%s", Total));
           
            try {
                String Extra = itemCmb.getSelectedIndex() >= 0 ? itemCmb.getSelectedItem().toString() : "Nothing";      //if NULL return NOTHING for Fries
                String s = String.format("insert into sales values (\"%s\", CURRENT_TIMESTAMP ,\"%s\", \"%s\", \"%s\", \"%s\", \"%s\")", OrderNo, item.getText(), Extra, itemQty.getText(), itemRate.getText(), totalLabel.getText());
                stmt.executeUpdate(s);
            } catch (Exception e) {
                System.out.println("Save sales record ERROR");
                e.printStackTrace();
            }
        }
        else if(!item.isSelected()){
            totalLabel.setText("0");
        }
        
    }
    
    public void justCalculate(JCheckBox item, JTextField itemQty, JTextField itemRate, JLabel totalLabel, JComboBox itemCmb){
        if (item.isSelected()){
           Total = itemCmb.getSelectedIndex() > 0 ? 10:0;
           Total += toInt(itemQty.getText()) * toInt(itemRate.getText());
           totalLabel.setText(String.format("%s", Total));
           
        }
        else if(!item.isSelected()){
            totalLabel.setText("0");
        }
        
    }
    
    
    public void changeRates(){
        txtChickenRate.setEditable(setRateEnable);
        txtVegRate.setEditable(setRateEnable);
        txtFriesRate.setEditable(setRateEnable);
        txtBurgerRate.setEditable(setRateEnable);
    }
    
    public void setRateValues(int chicken, int veg, int fries, int burger){ //To set Initial rate variables as JLabel text upon initialization.
        Chicken = chicken;                                                  //Check constructor for this method call.
        Veg = veg;
        Fries = fries;
        Burger = burger;
        
        txtChickenRate.setText(String.format("%s", Chicken));
        txtVegRate.setText(String.format("%s", Veg));
        txtFriesRate.setText(String.format("%s", Fries));
        txtBurgerRate.setText(String.format("%s", Burger));
    }
    
    private void storeToDB(){
        try {   //For the database update. STORING in database.
            stmt.executeUpdate("delete from rates");    //Every time this method is called it wipes old values and insert new ones.
            
            stmt.executeUpdate(String.format("insert into rates values(%s, %s, %s, %s)", Chicken, Veg, Fries, Burger));
        } catch (Exception e) {
            System.out.println("storeToDB exception");
            e.printStackTrace();
        }
    }
    
    private void readFromDB(){
        try {
            rs = stmt.executeQuery("select * from rates");
            rs.next();
            
            Chicken = rs.getInt("rateChicken");
            Veg = rs.getInt("rateVeg");
            Fries = rs.getInt("rateFries");
            Burger = rs.getInt("rateBurger");
            setRateValues(Chicken, Veg, Fries, Burger);
        } catch (Exception e) {
            System.out.println("read from db error");
            e.printStackTrace();
        }
    }
    
    public int toInt(String r){
        int rate;
        
        rate = Integer.parseInt(r);
        
        return rate;
    }
    
    private void databaseConnect(){
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcornerdb", "root", "");
            stmt = conn.createStatement();
        } catch (Exception e) {
            System.out.println("Error in databaseConnect()");
            e.printStackTrace();
        }
    }
    
    private void setLastOrderNo(){
        try {
            rs = stmt.executeQuery("SELECT MAX(Order_No) FROM sales");
            rs.next();
            OrderNo = rs.getInt("MAX(Order_No)");
            lblLastOrderNo.setText(String.format("%s", OrderNo));
            lblCurrOrderNo1.setText(String.format("%s", OrderNo + 1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Last Order no FETCH ERROR");
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEditRates;
    private javax.swing.JButton btnGetChange;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkBurger;
    private javax.swing.JCheckBox chkChicken;
    private javax.swing.JCheckBox chkFries;
    private javax.swing.JCheckBox chkVeg;
    private javax.swing.JComboBox<String> cmbBurgerAdd;
    private javax.swing.JComboBox<String> cmbChickenAdd;
    private javax.swing.JComboBox<String> cmbVegAdd;
    private javax.swing.JLabel lblBurgerTotal;
    private javax.swing.JLabel lblChickenTotal;
    private javax.swing.JLabel lblCurrOrderNo1;
    private javax.swing.JLabel lblFriesTotal;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblLastOrderNo;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrder1;
    private javax.swing.JLabel lblOrders;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel lblTotal3;
    private javax.swing.JLabel lblTotal4;
    private javax.swing.JLabel lblTotal5;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblType1;
    private javax.swing.JLabel lblVegTotal;
    private javax.swing.JTextField txtAmtChange;
    private javax.swing.JTextField txtAmtRecvd;
    private javax.swing.JTextField txtBurgerQty;
    private javax.swing.JTextField txtBurgerRate;
    private javax.swing.JTextField txtChickenQty;
    private javax.swing.JTextField txtChickenRate;
    private javax.swing.JTextField txtFriesQty;
    private javax.swing.JTextField txtFriesRate;
    private javax.swing.JTextField txtVegQty;
    private javax.swing.JTextField txtVegRate;
    // End of variables declaration//GEN-END:variables
}
