/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcorner;

import javax.swing.table.*;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author HIRAY-MCA
 */
public class ViewOrders extends javax.swing.JFrame {
    String columns[] = new String[7];
    DefaultTableModel model;
    String columnNames[] = {"Order_No", "Time", "Type", "Extra", "Qty", "Rate", "Total"};
    ButtonGroup group;
    
//------Database stuff-------
    Connection conn;
    Statement stmt;
    ResultSet rs;
    
    /**
     * Creates new form ViewOrders
     */
    public ViewOrders() {
        initComponents();
        setVisible(true);
        
        databaseConnect();
        forTable();
        
        group = new ButtonGroup();
        group.add(radioAllRecords); group.add(radioByDate); group.add(radioByOrderNo);
        
            txtFrom.setEnabled(false);
            txtTo.setEnabled(false);
            txtOrderNo.setEnabled(false);
    }
    
    private void forTable(){    //Initial table. Showing all records
        model = new DefaultTableModel();
        
        model.setColumnIdentifiers(columnNames);
        
        table.setModel(model);
        
        try {
            rs = stmt.executeQuery("select * from sales");
            
            setTable(rs);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR Table Read Data \n forTable()");
            e.printStackTrace();
        }
    }
    
    private void resetTable(){
        model.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnShowRecords = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radioAllRecords = new javax.swing.JRadioButton();
        lblFrom = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        radioByDate = new javax.swing.JRadioButton();
        radioByOrderNo = new javax.swing.JRadioButton();
        lblTo1 = new javax.swing.JLabel();
        txtOrderNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View All Orders");

        btnShowRecords.setText("Show Records");
        btnShowRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowRecordsActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        radioAllRecords.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioAllRecords.setSelected(true);
        radioAllRecords.setText("All Records");
        radioAllRecords.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioAllRecordsItemStateChanged(evt);
            }
        });

        lblFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFrom.setText("From:");

        txtFrom.setText("YYYY-MM-DD");
        txtFrom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFromMouseClicked(evt);
            }
        });
        txtFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRangeActionPerformed(evt);
            }
        });

        txtTo.setText("YYYY-MM-DD");
        txtTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRangeActionPerformed(evt);
            }
        });

        lblTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTo.setText("To:");

        radioByDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioByDate.setText("By Date");
        radioByDate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioByDateStateChanged(evt);
            }
        });

        radioByOrderNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioByOrderNo.setText("By Order No");
        radioByOrderNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioByOrderNoItemStateChanged(evt);
            }
        });

        lblTo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTo1.setText("Order No:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioByOrderNo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(radioAllRecords)
                    .addComponent(radioByDate)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTo1)
                        .addGap(18, 18, 18)
                        .addComponent(txtOrderNo)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(radioAllRecords)
                .addGap(55, 55, 55)
                .addComponent(radioByDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(radioByOrderNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtOrderNo)
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnShowRecords)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnShowRecords)
                .addGap(74, 74, 74))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRecordsActionPerformed
        if(radioAllRecords.isSelected()){
        resetTable();
        forTable();
        }
        else if(radioByDate.isSelected()){
            rangeRecords();
        }
        else if(radioByOrderNo.isSelected()){
            orderNoRecords();
        }
    }//GEN-LAST:event_btnShowRecordsActionPerformed

    private void btnRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRangeActionPerformed
        /*btnRange has been deleted.
            But this handler is still connected to txtFrom and txtTo when user presses Enter key*/
        rangeRecords();
    }//GEN-LAST:event_btnRangeActionPerformed

    private void txtFromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFromMouseClicked
        txtFrom.setText("");
        txtTo.setText("");
    }//GEN-LAST:event_txtFromMouseClicked

    private void radioByDateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioByDateStateChanged
        forRadioItemStateChanged();
    }//GEN-LAST:event_radioByDateStateChanged

    private void radioAllRecordsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioAllRecordsItemStateChanged
        forRadioItemStateChanged();
    }//GEN-LAST:event_radioAllRecordsItemStateChanged

    private void radioByOrderNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioByOrderNoItemStateChanged
        forRadioItemStateChanged();
    }//GEN-LAST:event_radioByOrderNoItemStateChanged

    private void forRadioItemStateChanged(){
        if(radioByDate.isSelected()){
            txtFrom.setEnabled(true);
            txtTo.setEnabled(true);
            txtOrderNo.setEnabled(false);
        }
        else if(radioByOrderNo.isSelected()){
            txtFrom.setEnabled(false);
            txtTo.setEnabled(false);
            txtOrderNo.setEnabled(true);
        }
        else{
            txtFrom.setEnabled(false);
            txtTo.setEnabled(false);
            txtOrderNo.setEnabled(false);
        }
    }
    
    private void rangeRecords(){
        try {
            String sql = "SELECT * FROM `sales` WHERE Time >= '" + txtFrom.getText() + "' AND Time < '" + txtTo.getText() + "'";
            rs = stmt.executeQuery(sql);

            setTable(rs);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR Range Records");
            e.printStackTrace();
        }
    }
    
    private void orderNoRecords(){
        try {
            rs = stmt.executeQuery("select * from sales where Order_No = " + txtOrderNo.getText());
            setTable(rs);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR in Record by Order No");
            e.printStackTrace();
        }
    }
    
    private void setTable(ResultSet rss){
        resetTable();
        
        try {
            while(rss.next()){
                
                for(int i=0;i<columns.length;i++){  //add 1 Row of record to columns[]
                    columns[i] = rs.getString(columnNames[i]);  //columnIdentifiers same as names of columns in DB
                }
                
                model.addRow(columns);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR in setTable()");
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrders().setVisible(true);
            }
        });
    }
    
    private void databaseConnect(){
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcornerdb", "root", "");
            stmt = conn.createStatement();
        } catch (Exception e) {
            System.out.println("Error in databaseConnect()");
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowRecords;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblTo1;
    private javax.swing.JRadioButton radioAllRecords;
    private javax.swing.JRadioButton radioByDate;
    private javax.swing.JRadioButton radioByOrderNo;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtOrderNo;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
